README.md
custom_components/mitsubishi/climate.py
custom_components/mitsubishi/const.py
custom_components/mitsubishi/manifest.json
custom_components/mitsubishi/sensor.py
hacs.json
info.md

Merge Experimental with master

Experimental

---

custom_components/mitsubishi/climate.py
custom_components/mitsubishi/manifest.json
custom_components/mitsubishi/sensor.py

Experimental into Master

---

custom_components/echonetlite/__init__.py
custom_components/echonetlite/climate.py
custom_components/echonetlite/config_flow.py
custom_components/echonetlite/const.py
custom_components/echonetlite/manifest.json
custom_components/echonetlite/select.py
custom_components/echonetlite/sensor.py

Implement long term stats changes to sensor class
**Draft** changes to support a cumulative power sensor (awaiting pychonet update)
Update device name to match the user's configured name in config flow
Prefix entity names to include user's configured name to prevent conflicts in names and ids when multiple devices of the same class exist

Long term stats, cumulative energy & manufacturer info

---

custom_components/echonetlite/config_flow.py
custom_components/echonetlite/manifest.json

This PR aims to correctly display the manufacturer of the device.
This PR should be merged after https://github.com/scottyphillips/pychonet/pull/9 is merged. I believe `pychonet` will be bumped to `2.0.13`. Thank you!

Get manufacturer information

---

custom_components/echonetlite/__init__.py
custom_components/echonetlite/config_flow.py
custom_components/echonetlite/light.py

Hi,
pull request for home assistant light entity. Brightness has been working for year at my side, the color temp I am not sure, as I just started to use the new code. I did my best to map those echonet color classes to the minreds.
However, the whole code crashes when setting up in home assistant. Seems it does not handle multiple instance under one host properly. I will create a issue for it.
Best

adding the light wrapper for echonetlite general lighting class

---

custom_components/echonetlite/__init__.py
custom_components/echonetlite/config_flow.py
custom_components/echonetlite/light.py

Hi,
This code is in production since 1 day and it works. Brightness and color temperature can be set and are read/mapped correctly to HA.
When the crashed in pychonet are fixed, we can remove this ugly hack in the config_flow

Merging working echonetlite light

---

README.md

Testing and working on these two units.

Added info on supported units

---

README.md

Closes https://github.com/scottyphillips/echonetlite_homeassistant/issues/54

Add another supported device

---

custom_components/echonetlite/__init__.py
custom_components/echonetlite/config_flow.py
custom_components/echonetlite/const.py
custom_components/echonetlite/fan.py
custom_components/echonetlite/select.py
custom_components/echonetlite/sensor.py

add air cleaner support 
add a fan entity for home assistant.

add air cleaner support

---

README.ja.md
Services.ja.md
custom_components/echonetlite/translations/ja.json
custom_components/echonetlite/translations/sensor.ja.json

Added *.ja.* files for Japanese translation

---

custom_components/echonetlite/__init__.py
custom_components/echonetlite/climate.py
custom_components/echonetlite/fan.py
custom_components/echonetlite/light.py
custom_components/echonetlite/select.py
custom_components/echonetlite/sensor.py
custom_components/echonetlite/switch.py

Bug fixes and optimizations for the push state feature.
Changed the register_async_update_callbacks() function from EchonetInstance to ECHONETConnector. So you don't need EchonetInstance.register_async_update_callbacks().
https://github.com/scottyphillips/pychonet/blob/828b9f14b4ae8a9fcd6962f1919e6b8487ec4b6e/pychonet/EchonetInstance.py#L278-L279

Bugfix and optimization of states push feature

---

custom_components/echonetlite/const.py

build const of lock switch

---

custom_components/echonetlite/const.py
custom_components/echonetlite/switch.py

Increased switch redundancy to support as many types as possible.

Enhanced switch mediocrity

---

custom_components/echonetlite/const.py
custom_components/echonetlite/sensor.py
custom_components/echonetlite/services.yaml

I have added a single byte integer value setting service.
The service is enabled only if the corresponding parameter can be set.
Error handling works better with https://github.com/scottyphillips/pychonet/pull/51.

Added single-byte integer value setting service

---

custom_components/echonetlite/__init__.py
custom_components/echonetlite/config_flow.py

see [pychonet PR #49](https://github.com/scottyphillips/pychonet/pull/49)

Support pychonet PR #49

---

custom_components/echonetlite/services.yaml

I fixed validate error  with hassfest.
ref. https://github.com/nao-pon/echonetlite_homeassistant/actions/workflows/hassfest.yaml

Remove invalid key of services.yaml

---

custom_components/echonetlite/__init__.py

see.
https://developers.home-assistant.io/blog/2022/07/08/config_entry_forwards/

use `async_forward_entry_setups`

---

custom_components/echonetlite/const.py

add support for home battery storage

add support for home battery storage 

---

custom_components/echonetlite/const.py
custom_components/echonetlite/sensor.py

change Home solar power generation and home battery storage icon to dynamic. I very cool at lovelace gui.
look like this

change Home solar power generation and home battery storage icon

---

custom_components/echonetlite/__init__.py
custom_components/echonetlite/config_flow.py
custom_components/echonetlite/const.py
custom_components/echonetlite/translations/en.json
custom_components/echonetlite/translations/ja.json

Rel. https://github.com/scottyphillips/echonetlite_homeassistant/issues/150

Automatic adjustment of maximum number of batch requests (OPC number)

---

custom_components/echonetlite/__init__.py
custom_components/echonetlite/climate.py
custom_components/echonetlite/config_flow.py
custom_components/echonetlite/const.py
custom_components/echonetlite/fan.py
custom_components/echonetlite/light.py
custom_components/echonetlite/number.py
custom_components/echonetlite/select.py
custom_components/echonetlite/sensor.py
custom_components/echonetlite/switch.py
custom_components/echonetlite/time.py
custom_components/echonetlite/translations/en.json
custom_components/echonetlite/translations/ja.json

This also includes modifications to the switch and select entity components.
This requires PR changes to pychonet, but it also allows automatic configuration of switch, select, and time entities.
- https://github.com/scottyphillips/pychonet/pull/68

Add Number, Time, Input entity component

---

README.md

Spent hours trying to workout why module was not working, only to remember my NixOS firewall and I had to add 3610.

Update README to include MAC-588IF-E support and port 3610

---

custom_components/echonetlite/__init__.py
custom_components/echonetlite/const.py
custom_components/echonetlite/cover.py
custom_components/echonetlite/manifest.json
custom_components/echonetlite/number.py
custom_components/echonetlite/select.py
custom_components/echonetlite/switch.py
custom_components/echonetlite/time.py

Maintenance related to pull request #174

Maintaining the Cover entity

---

README.md

Also a note about temperature precision.

List a couple more supported models

---

custom_components/echonetlite/const.py

Add Bathroom dryer

---

custom_components/echonetlite/const.py

Fix #202 Correctly defining water level sensors

---

custom_components/echonetlite/const.py

Support Multiple Input PCS

---

custom_components/echonetlite/__init__.py
custom_components/echonetlite/const.py
custom_components/echonetlite/number.py
custom_components/echonetlite/quirks/Nichicon/all/02A5.py
custom_components/echonetlite/quirks/Panasonic/all/0135.py
custom_components/echonetlite/select.py
custom_components/echonetlite/sensor.py
custom_components/echonetlite/switch.py
custom_components/echonetlite/time.py

Allows definition of each manufacturer's quirks
